name: Android CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: gradle/wrapper-validation-action@v1
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew assembleRelease

    - name: Upload a Build Artifact (full)
      uses: actions/upload-artifact@v2.3.1
      with:
        name: full
        path: app/build/outputs/apk/full/release/*.apk

    - name: Upload a Build Artifact (eng)
      uses: actions/upload-artifact@v2.3.1
      with:
        name: eng
        path: app/build/outputs/apk/english-only/release/*.apk

  release:
    name: Release APK
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download APK from build (full)
        uses: actions/download-artifact@v1
        with:
          name: full

      - name: Download APK from build (eng)
        uses: actions/download-artifact@v1
        with:
          name: eng

      - name: Automatic Releases
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: "latest"
          prerelease: false
          files: |
            full/*.apk
            eng/*.apk
